title: akari.io
description: >
  研究についてのメモと日常のつぶやき
baseurl: ""
url: "https://http://akari000.github.io"

author:
  name: akari
  email: 
  github: akari000
  twitter: _akari000

paginate: 5
paginate_path: page:num

sass:
  style: expanded

gems:
  - jekyll-paginate
  - jekyll-feed