title: akari.io
description: >
baseurl: ""
url: "https://http://akari000.github.io"

author:
  name: akari
  email: haga.akari.ha0@is.naist.jp
  github: akari000
  twitter: _akari000

paginate: 3
paginate_path: page:num

sass:
  style: expanded

plugins:
  - jekyll-paginate
  - jekyll-feed
